version: '3.12'

services:
  web:
    build: .
    container_name: blogpost-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/views
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=0.0.0.0,127.0.0.1,localhost
